### ISSUE TITLE
Automatic analysis not shown in Dashboard

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat-dashboard#10]
Er lijkt iets mis te gaan met de automatische coderingen in het Dashboard. Ergens geeft dashboard foutmeldingen bij het laden. zie bijlage
<img width="960" alt="screenshot 2018-07-28 14 09 49" src="https://user-images.githubusercontent.com/6438205/43357391-02e1d5ac-9281-11e8-8a2c-2ca24ea8cd29.png">

**Comment by nruigrok** [comment]
Het gaat over met het ophalen van een nieuwe token via de AmCAT settings! Idealiter zou dat wel automatisch gebeuren...

Hieronder de log:


```
WARNING:root:Cannot renew token (requires amcat>3.5), trying normal authentication: [Errno 401] Request 'http://bzk.nieuwsmonitor.org/api/v4/get_token?format=json' returned code 401, expected 200. 
{"exception_type":"AuthenticationFailed","detail":"The token expired on 2018-07-26 11:43:24.512817. Please request a new token."}: 'http://bzk.nieuwsmonitor.org/api/v4/get_token?format=json': None; None
WARNING:root:Cannot renew token (requires amcat>3.5), trying normal authentication: [Errno 401] Request 'http://bzk.nieuwsmonitor.org/api/v4/get_token?format=json' returned code 401, expected 200. 
{"exception_type":"AuthenticationFailed","detail":"The token expired on 2018-07-26 11:43:24.512817. Please request a new token."}: 'http://bzk.nieuwsmonitor.org/api/v4/get_token?format=json': None; None
ERROR:django.request:Internal Server Error: /dashboard/page/5/get_saved_query/40
Traceback (most recent call last):
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "./dashboard/views/dashboard_view.py", line 120, in get_saved_query
    "amcat_options": query.get_options(),
  File "./dashboard/models/query.py", line 134, in get_options
    self.update_options()
  File "./dashboard/models/query.py", line 173, in update_options
    r = get_session(self.system).options(url)
  File "./dashboard/util/api.py", line 85, in get_session
    return ApiSession(system=system)
  File "./dashboard/util/api.py", line 34, in __init__
    token = system.get_api().token  # refreshes token as side effect
  File "./dashboard/models/system.py", line 70, in get_api
    return AmcatAPI(host=self.hostname, token=self.amcat_token)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/amcatclient/amcatclient.py", line 153, in __init__
    self.token, self.version = self.get_token(user, password)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/amcatclient/amcatclient.py", line 198, in get_token
    user, password = self._get_auth()
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/amcatclient/amcatclient.py", line 188, in _get_auth
    "variables".format(**locals()))
Exception: No authentication info for None@http://bzk.nieuwsmonitor.org from /home/amcat/.amcatauth or AMCAT_USER / AMCAT_PASSWORD variables
```
