### ISSUE TITLE
dashboard shows "blank template" page instead of proper error

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat-dashboard#12]
E.g. at the moment http://dashboard.bzk.nieuwsmonitor.org/dashboard/page/5/get_saved_query_result/26?q=ollongren gives an error (probably an R problem, so probably my problem ;-)). The dashboard doesn't show a normal error page however, but a HTTP 500 with a message about the base templatae, presumably from the bootstrap theme. 

![image](https://user-images.githubusercontent.com/1736240/45211809-8f5d6780-b293-11e8-8a67-249f07555297.png)

(error was:
```
ERROR:django.request:Internal Server Error: /dashboard/page/5/get_saved_query_result/26
Traceback (most recent call last):
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/dashboard_bzk/amcat-dashboard/env/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "./dashboard/views/dashboard_view.py", line 147, in get_saved_query_result
    return get_filtered_query_result(request, cache)
  File "./dashboard/views/dashboard_view.py", line 182, in get_filtered_query_result
    content, content_type = query_cache.poll(uuid, save_result=False)
  File "./dashboard/models/query.py", line 249, in poll
    result = poll(get_session(self.query.system), uuid)
  File "./dashboard/util/api.py", line 77, in poll
    return session.poll(*args, **kwargs)
  File "./dashboard/util/api.py", line 50, in poll
    return self.poll(uuid, timeout=min(timeout * 2, max_timeout))
  File "./dashboard/util/api.py", line 52, in poll
    raise ValueError("Task {!r} failed.".format(uuid))
ValueError: Task '61807b52-010a-44ea-9914-e77106b586ab' failed.
[pid: 6315|app: 0|req: 55/200] 145.108.78.195 () {44 vars in 1037 bytes} [Fri Sep  7 09:44:01 2018] GET /dashboard/page/5/get_saved_query_result/26?q=ollongren => generated 132 bytes in 500 msecs (HTTP/1.1 500) 5 headers in 181 bytes (2 switches on core 0)
```

**Comment by CJStuart** [comment]
Relevant from pinax readme:

> Your "site_base.html" should extend "theme_base.html" and should provide
> "footer" and "nav" blocks (the latter should just be a ul of li of a links).
> 
> Your pages should have blocks "head_title" and "body" and should extend
> "site_base.html".
